### ISSUE TITLE
Exploration for sortable category groups

### ISSUE THREAD

**Issue by daafbleumink** [ttempleton/craft-category-groups-field#5]
Hi there,

Not really an issue on this side, but more of an explorative feature request.

Have you explored the possibility to make the category group field picker a sortable template?
It would require a custom inputhtml template and some way to store the sorting in the database.

Any ideas on how to approach this? Based off what you already built.

Looking forward to your ideas.

Cheers,

Daaf

**Comment by ttempleton** [comment]
I've just released 2.1.0 which makes multi-select category groups fields act basically like Craft's in-built multi-select field in more recent versions of Craft, but with the ability to drag and drop selected category groups.

It's a bit hacky in its implementation, in that I had to force the selected category groups to be the first options for the field when generating the input HTML, to get them to show in the selected order when loading an element editor page. This means that your category group options would be out of their natural order if you deselected the selected ones. Unfortunately - and I'm not quite sure whether this is up to the Selectize library or the Craft code setting up Selectize-using fields - I think this is the best I can do without making an entirely custom input HTML template, as you've suggested; and at this point I'm unlikely to do that for this plugin, since the [Craft entrification process](https://craftcms.com/blog/entrification) will make this plugin obsolete.
